Single Qubit Systems Measurements Tutorial created
microsoft/QuantumKatas pull request #570
Opened 2020-12-02 06:54 UTC by PratikSathe

Created the single qubit measurements tutorial. Contains 7 exercises.

2020-12-11 07:19 UTC, tcNickolas requested changes
I did a first pass and left some comments. I think addressing them should fix the CI build failure, and after that we'll only have the final round of polish to do, formatting and typos kind of things. I might do that myself as I go through the tutorial and the workbook for review - it's usually easier to fix such trivial things as I see them than to point them out in the review and do another iteration.

Thank you!

2020-12-11 07:19 UTC, tcNickolas commented on tutorials/SingleQubitSystemMeasurements/Tests.qs
> +            ["|psi-⟩", "|psi+⟩"], false);
You can use Unicode ψ₋ and ψ₊ here to be consistent with the task description, as long as they are not distorted by Jupyter Notebook output

2020-12-11 07:19 UTC, tcNickolas commented on tutorials/SingleQubitSystemMeasurements/Tests.qs
> +        // cross-test
You shouldn't need these comments, since you're not running tests for these special cases, just for the general one

2020-12-13 01:13 UTC, PratikSathe commented on tutorials/SingleQubitSystemMeasurements/SingleQubitSystemMeasurements.csproj
> +<Project Sdk="Microsoft.Quantum.Sdk/0.13.20111004">
Got it, I've made this change.

2020-12-13 01:14 UTC, PratikSathe commented on tutorials/SingleQubitSystemMeasurements/SingleQubitSystemMeasurements.csproj
> +    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
Got it, I've made this change!

2020-12-13 01:14 UTC, PratikSathe commented on tutorials/SingleQubitSystemMeasurements/Tests.qs
> +    @Test("Microsoft.Quantum.Katas.CounterSimulator")
This makes sense!

2020-12-13 01:15 UTC, PratikSathe commented on tutorials/SingleQubitSystemMeasurements/Tasks.qs
> +    operation IsQubitSpecificState (q : Qubit) : Bool {
That makes a lot of sense. By saying "SpecificState", I was not being specific at all, haha!

2020-12-13 01:19 UTC, PratikSathe commented on tutorials/SingleQubitSystemMeasurements/SingleQubitSystemMeasurements.ipynb
> +    "    mutable countOne = 0;\n",
That makes sense, I kept countOne and CountZero just to make it explicitly clear that exactly one of the counts will be increased after each measurement, but I agree that keeping just one count will make it shorter, so I've made this change.

2020-12-13 02:49 UTC, PratikSathe commented
Hi, @tcNickolas , thank you for all your suggestions! I have incorporated them now.

2020-12-15 23:28 UTC, PratikSathe commented
Hi @tcNickolas , I think I have addressed all of your requested changes. Please let me know if anything else needs to be done. Thank you!

2020-12-19 02:14 UTC, tcNickolas approved these changes
Looks great! I did some cleanup, fixing typos and such, and added the tutorial to the lists of others.

Thank you!

2020-12-19 02:19 UTC, merged